export const ADMIN_ROUTE = '/admin'
export const LOGIN = '/login'
export const REGISTRATION = '/registration'
export const DEVICE_ROUTE = '/device'
export const BASKET_ROUTE = '/basket'
export const SHOP_ROUTE = '/'